### PR TITLE
build: plugin 6.3.1, gradle 8.0.2, micronaut-validation module

### PR DESCRIPTION
**Pull request by wetted**

### CODE REVIEW

**Comment by wetted** [comment]
@melix I'm not sure what to do about the sonarcube failure. It's due to changes I had to make – to get the examples poject working – at https://github.com/micronaut-projects/micronaut-acme/pull/279/files#diff-7f825392aa37acd1cee0c2e7b9bb7366ad6eac64f3e6cdd816e156bcb69d30deR23

**Comment by melix** [comment]
@wetted if you use standardized project names, then only projects which name starts with `test-suite-` are not renamed. I'm not sure what those `examples` are, but I could add another exception to the rule (you are not forced to move to standardized project names _now_).

Regarding the validation failure, since validation has moved out of core, we are in a strange situation where the old Gradle plugin cannot be used anymore in test modules : you have to use 4.0.0-SNAPSHOT. However, I had to publish a SNAPSHOT version from a branch yesterday, because the version which supports the validation changes is still not merged because of other failures in data. Headache...

**Comment by wetted** [comment]
OK, thanks @melix. It sounds like I have to wait for the gradle plugin 4.0.0-SNAPSHOT to publish successfully. I have `useStandardizedProjectNames=true` following @sdelamo's example for the security module. I'll check back later. I have plenty of other modules to migrate too.

**Comment by sdelamo** [comment]
we could just rewrite docs-examples to test-suite and get around the issue.

**Comment by wetted** [comment]
@sdelamo This is ready now. @melix changed the build plugin to support it, and I updated the example gradle plugin to 4.0.0-SNAPSHOT, so now it pulls in the right validation dependencies.

I did not refactor the name of the example project to `docs-examples:test-suite` but can if you rather have it that way. However, it doesn't have any tests. It is just an example.

**Review by sdelamo — APPROVED** [review]

**Pull request merged**
